import { useContext, useEffect, useRef, useState } from "react";
import styled from "styled-components";
import { CardCssContext } from "../hooks/CardCSS";
import CSSPropVal from "./CSSPropVal";
import CodeHeader from "./CodeHeader";

const Code = () => {
  const { cardCss } = useContext(CardCssContext);
  const [genBoxS, setGenBoxS] = useState(0);
  const codeRef = useRef(null);

  const ifBorderRadius = () => {
    const br = cardCss.borderRadius;
    return (
      br.topLeft.x.value ||
      br.topLeft.y.value ||
      br.topRight.x.value ||
      br.topRight.y.value ||
      br.bottomRight.x.value ||
      br.bottomRight.y.value ||
      br.bottomLeft.x.value ||
      br.bottomLeft.y.value
    );
  };

  const borderRadiusCSSValue = `${cardCss.borderRadius.topLeft.y.value}${
    cardCss.borderRadius.topLeft.y.unit
  } ${cardCss.borderRadius.topRight.y.value}${
    cardCss.borderRadius.topRight.y.unit
  } ${-cardCss.borderRadius.bottomRight.y.value}${
    cardCss.borderRadius.bottomRight.y.unit
  } ${-cardCss.borderRadius.bottomLeft.y.value}${
    cardCss.borderRadius.bottomLeft.y.unit
  } / ${cardCss.borderRadius.topLeft.x.value}${
    cardCss.borderRadius.topLeft.x.unit
  } ${-cardCss.borderRadius.topRight.x.value}${
    cardCss.borderRadius.topRight.x.unit
  } ${-cardCss.borderRadius.bottomRight.x.value}${
    cardCss.borderRadius.bottomRight.x.unit
  } ${cardCss.borderRadius.bottomLeft.x.value}${
    cardCss.borderRadius.bottomLeft.x.unit
  }`;

  useEffect(() => {
    let noBoxShadow = true;
    Object.keys(cardCss.boxShadow).forEach((item) => {
      const { x, y, blur, spread } = cardCss.boxShadow[item];
      noBoxShadow = !(x || y || blur || spread);
    });

    if (noBoxShadow) {
      setGenBoxS("");
    } else {
      setGenBoxS(
        Object.values(cardCss.boxShadow)
          .map((shadow, i) => {
            return `${shadow.inset ? "inset" : ""} ${shadow.x}px ${
              shadow.y
            }px ${shadow.blur}px ${shadow.spread}px ${shadow.color}${
              i >= Object.values(cardCss.boxShadow).length - 1 ? "" : ", "
            }`;
          })
          .join("")
      );
    }
  }, [cardCss.boxShadow]);

  return (
    <Div>
      <CodeHeader codeRef={codeRef} />
      <Pre>
        <code ref={codeRef}>
          .card {"{"}
          <p style={{ overflow: "hidden", height: 0, opacity: "0" }}>
            {"/* Generated by PerfectCard.io */"}
          </p>
          <Comment>{"/* Basic Styles */"}</Comment>
          <CSSPropVal
            prop="width"
            val={`${Math.round(cardCss.width)}${cardCss.widthUnit}`}
          />
          <CSSPropVal
            prop="height"
            val={`${Math.round(cardCss.height)}${cardCss.heightUnit}`}
          />
          <CSSPropVal prop="background-color" val={cardCss.bgColor} />
          {ifBorderRadius() || cardCss.allBorderRadius ? (
            <>
              <br />
              <Comment>{"/* Border Radius */"}</Comment>

              <CSSPropVal
                prop="border-radius"
                val={
                  cardCss.allBorderRadius
                    ? `${cardCss.allBorderRadius}${cardCss.allBorderRadiusUnit}`
                    : borderRadiusCSSValue
                }
              />
            </>
          ) : undefined}
          {genBoxS && (
            <>
              <br />
              <Comment>{"/* Box Shadow */"}</Comment>
              <CSSPropVal prop="box-shadow" val={genBoxS} />
            </>
          )}
          {"}"}
        </code>
      </Pre>
    </Div>
  );
};

const Div = styled.div`
  background-color: rgb(var(--bg-main));
  border-radius: 0.5rem;
  border: 1px solid rgb(var(--gray));
`;

const Comment = styled.div`
  color: rgb(var(--gray));
  padding-inline-start: 1.5rem;
`;

const Pre = styled.pre`
  padding: 1.5rem;
`;

export default Code;
